### ISSUE TITLE
Define requirements for the Oversight Committee role

### ISSUE THREAD

**Issue by scottrigby** [fluxcd/community#106]
The Oversight Committee was initially be comprised of Flux Maintainers who have steered the project prior to the initial Governance document <https://github.com/fluxcd/community/blob/main/GOVERNANCE.md>.

The aspiration is that no one company or organization should have oversight of the overall project, however that was not yet realistic at the initial stage. The goal is to broaden maintainership to include a wider range of organizations during CNCF incubation.

To aid in this goal, we aim to build out requirements for the Oversight Committee role during incubation.

See #75

**Comment by kingdonb** [comment]
I think this meant to follow up #75 (that was merged)

How can we help move this along, since that one was merged?

(I see some looks like bad links related to this: https://fluxcd.io/community/#teams)

![Screen Shot 2021-07-22 at 1 36 31 PM](https://user-images.githubusercontent.com/3286998/126683684-4d2d23ad-9722-45f0-8d5b-cabd221ceefc.png)

**Comment by dholbach** [comment]
Since our governance overhaul together with WG Governance, this can be closed. If there are any new concerns with our setup with Core Maintainers and Org Admins, please open a new issue.
