### ISSUE TITLE
Flux Pull Request merge policy

### ISSUE THREAD

**Issue by scottrigby** [fluxcd/community#16]
Clarify the Flux project's policy on pull request requirements for merging, including when and when not to squash commits.

1. From quick chat, my understanding is the current maintainer preference is for PR authors to squash commits into understandable units of work. This could include history of working through a problem if there is a possibility that the older work may need to be referenced for any reason.
2. GitHub provides enabling one or more merge methods per repo: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuring-pull-request-merges
    - Currently only merge commits are allowed on this repo
    - We could enforce squashed commits always by enabling only that option
    - Or we could enable either, and set a loose policy for when a Maintainer chooses one or the other
    - IMO the one problematic thing about requiring users to squash their own PR branch and force-push is that GitHub review comments can lose context when commit SHAs change. But the GitHub squash merge option retains review comments as the fork branch itself is not changed, commits are only squashed during the merge operation

**Comment by scottrigby** [comment]
@hiddeco mentioned this file as a place where commits/merge policy could be clarified: <https://github.com/fluxcd/flux/blob/master/CONTRIBUTING.md#acceptance-policy>

**Comment by kingdonb** [comment]
I think we prefer to squash commits so that history can remain linear, and only keep commit histories on branches that are really important outside of the context of the branch.

I've had good luck with force pushing over branches and resolving the conflict where users have left their commit history intact but in need of rebase, or intact with some issues, to expedite merging.

Lots of time has passed since this was open, I don't think this discussion is active anymore.
