### ISSUE TITLE
Specify "Decision log" in governance doc

### ISSUE THREAD

**Issue by squaremo** [fluxcd/community#18]
It's important to have an audit trail for decisions, especially those made over governance. I propose we figure out a way to log decisions in some reasonably verifiable way -- commits with signatures come to mind. Whatever is figured out should be explained in the governance doc.

**Comment by scottrigby** [comment]
About logging decisions:
> All proposals should be discussed publicly in an appropriate GitHub issue or pull request.

That only applies to proposals, but the decision guidelines also say:
> Decisions that warrant wider input should be made public by using the below guidelines in combination with the Proposal Process below.

So anything warranting wider input must be done publicly this way. Does that seem like enough?

About verifiability, I would argue that a yes/no comment from a maintainer's account is enough. If we don't trust the maintainers to set their GitHub account securely, a PGP signed commit won't help – because a compromised account could just add a fake PGP key to the account anyway.

WDYT?

**Comment by alisondy** [comment]
Hello hello,
My thoughts

- mailing list can be decision register
  - you send a message to the mailing list when you're adding someone to maintainers
  - set it to 7 day lazy consensus
  - after 7 day consensus, reply to same thread saying, consensus finished, PR merged

benefits  
- Keeps decisions separate from git / everything else happening in git
- Emails are hard to impersonate to some degree
- Makes decisions searchable via email, google group

**Comment by kingdonb** [comment]
I think the RFC process addressed this with:

* https://github.com/fluxcd/flux2/tree/main/rfcs
* referenced from https://github.com/fluxcd/community/blob/main/PROCESS.md

Commits are signed, I'm not sure what remains to be done if anything, but feel free to reopen if needed! 🌻
